/**
 * Risk Engine Service — Phase 4
 *
 * Deterministic risk rules applied after actual changes are recorded.
 * Covers: FILE_OVERLAP, SCOPE_EXPANSION.
 * CONTRACT_CHANGE risks are generated by contract-change.service.ts.
 */
import { prisma } from '@arxion/database'
import { emitEvent } from '../../lib/realtime.js'

/**
 * Run deterministic risk rules for a task after actual changes are processed.
 */
export async function runRiskEngine(opts: {
  projectId: string
  taskId: string
  actualFilePaths: string[]
}): Promise<void> {
  const { projectId, taskId, actualFilePaths } = opts

  await checkFileOverlapRisks(projectId, taskId, actualFilePaths)
  await checkScopeExpansionRisk(projectId, taskId, actualFilePaths)
}

// ─── FILE_OVERLAP ─────────────────────────────────────────────────────────────

/**
 * If Git shows a task actually modifying a file that another active task
 * has reserved, generate a FILE_OVERLAP CoordinationRisk.
 */
async function checkFileOverlapRisks(
  projectId: string,
  taskId: string,
  actualFilePaths: string[],
): Promise<void> {
  if (actualFilePaths.length === 0) return

  for (const filePath of actualFilePaths) {
    const conflictingReservations = await prisma.taskFileReservation.findMany({
      where: {
        projectId,
        filePath,
        status: 'ACTIVE',
        NOT: { taskId },
      },
      include: { task: { select: { id: true, displayId: true, status: true } } },
    })

    for (const reservation of conflictingReservations) {
      if (!['IN_PROGRESS', 'REVIEW'].includes(reservation.task.status)) continue

      const existing = await prisma.coordinationRisk.findFirst({
        where: {
          projectId,
          sourceTaskId: taskId,
          affectedTaskId: reservation.task.id,
          type: 'FILE_OVERLAP',
          status: 'OPEN',
        },
      })
      if (existing) continue

      const sourceTask = await prisma.task.findUnique({
        where: { id: taskId },
        select: { displayId: true },
      })

      const risk = await prisma.coordinationRisk.create({
        data: {
          projectId,
          sourceTaskId: taskId,
          affectedTaskId: reservation.task.id,
          type: 'FILE_OVERLAP',
          severity: 'MEDIUM',
          confidence: 'HIGH',
          title: `File overlap: ${filePath}`,
          description: `Task ${sourceTask?.displayId ?? taskId} actually modified "${filePath}", which is also reserved by task ${reservation.task.displayId}.`,
          status: 'OPEN',
        },
      })

      emitEvent('risk.created', projectId, {
        riskId: risk.id,
        type: 'FILE_OVERLAP',
        sourceTaskId: taskId,
        affectedTaskId: reservation.task.id,
        filePath,
      })

      // Coordination metric
      await prisma.taskActivity.create({
        data: {
          projectId,
          taskId,
          type: 'risk.created',
          message: `File overlap risk: "${filePath}" modified by multiple tasks`,
          metadata: { riskId: risk.id, riskType: 'FILE_OVERLAP', affectedTaskId: reservation.task.id, filePath },
        },
      })
    }
  }
}

// ─── SCOPE_EXPANSION ─────────────────────────────────────────────────────────

/**
 * If actual files include files not in the declared work intent,
 * generate a SCOPE_EXPANSION risk if any of those files are active elsewhere.
 */
async function checkScopeExpansionRisk(
  projectId: string,
  taskId: string,
  actualFilePaths: string[],
): Promise<void> {
  const intent = await prisma.taskWorkIntent.findUnique({ where: { taskId } })
  if (!intent) return

  const declared = new Set(intent.files)
  const undeclared = actualFilePaths.filter((f) => !declared.has(f))
  if (undeclared.length === 0) return

  // Check if undeclared files are owned by another task
  for (const filePath of undeclared) {
    const otherTasks = await prisma.taskFileReservation.findMany({
      where: {
        projectId,
        filePath,
        status: 'ACTIVE',
        NOT: { taskId },
      },
      include: { task: { select: { id: true, displayId: true, status: true } } },
    })

    for (const reservation of otherTasks) {
      if (!['IN_PROGRESS', 'REVIEW'].includes(reservation.task.status)) continue

      const existing = await prisma.coordinationRisk.findFirst({
        where: {
          projectId,
          sourceTaskId: taskId,
          affectedTaskId: reservation.task.id,
          type: 'SCOPE_EXPANSION',
          status: 'OPEN',
        },
      })
      if (existing) continue

      const sourceTask = await prisma.task.findUnique({
        where: { id: taskId },
        select: { displayId: true },
      })

      const risk = await prisma.coordinationRisk.create({
        data: {
          projectId,
          sourceTaskId: taskId,
          affectedTaskId: reservation.task.id,
          type: 'SCOPE_EXPANSION',
          severity: 'HIGH',
          confidence: 'HIGH',
          title: `Scope expansion: unexpected file ${filePath}`,
          description: `Task ${sourceTask?.displayId ?? taskId} unexpectedly modified "${filePath}" (not declared in work intent), which is also reserved by task ${reservation.task.displayId}.`,
          status: 'OPEN',
        },
      })

      emitEvent('risk.created', projectId, {
        riskId: risk.id,
        type: 'SCOPE_EXPANSION',
        sourceTaskId: taskId,
        affectedTaskId: reservation.task.id,
        filePath,
      })
    }
  }
}

// ─── Risk queries ─────────────────────────────────────────────────────────────

/**
 * Get all open CoordinationRisks for a project.
 */
export async function getProjectRisks(projectId: string, status?: string) {
  return prisma.coordinationRisk.findMany({
    where: {
      projectId,
      status: (status as 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED' | 'DISMISSED') ?? 'OPEN',
    },
    include: {
      sourceTask: { select: { id: true, displayId: true, title: true } },
      affectedTask: { select: { id: true, displayId: true, title: true } },
      sourceEntity: { select: { id: true, name: true, type: true, filePath: true } },
    },
    orderBy: [{ severity: 'desc' }, { detectedAt: 'desc' }],
  })
}

/**
 * Get risks for a specific task (as source or affected).
 */
export async function getTaskRisks(taskId: string) {
  const task = await prisma.task.findFirst({
    where: { OR: [{ id: taskId }, { displayId: taskId }] },
  })
  if (!task) throw Object.assign(new Error(`Task not found: ${taskId}`), { statusCode: 404 })

  return prisma.coordinationRisk.findMany({
    where: {
      OR: [{ sourceTaskId: task.id }, { affectedTaskId: task.id }],
      status: 'OPEN',
    },
    include: {
      sourceTask: { select: { id: true, displayId: true, title: true } },
      affectedTask: { select: { id: true, displayId: true, title: true } },
      sourceEntity: { select: { id: true, name: true, type: true } },
    },
    orderBy: [{ severity: 'desc' }, { detectedAt: 'desc' }],
  })
}

/**
 * Acknowledge or dismiss a risk.
 * Optionally pass projectId to enforce cross-project access control.
 */
export async function acknowledgeRisk(
  riskId: string,
  status: 'ACKNOWLEDGED' | 'DISMISSED',
  callerProjectId?: string,
) {
  const risk = await prisma.coordinationRisk.findUnique({ where: { id: riskId } })
  if (!risk) throw Object.assign(new Error(`Risk not found: ${riskId}`), { statusCode: 404 })

  // Cross-project access guard
  if (callerProjectId && risk.projectId !== callerProjectId) {
    throw Object.assign(new Error('Access denied: risk belongs to a different project.'), { statusCode: 403 })
  }

  const updated = await prisma.coordinationRisk.update({
    where: { id: riskId },
    data: {
      status,
      resolvedAt: status === 'DISMISSED' ? new Date() : null,
    },
  })

  emitEvent('risk.updated', risk.projectId, { riskId, status })
  return updated
}
